export { addBackgroundListener, callBackground } from './_callBackground'
export { $w } from './_dom'
export { escapeHtml, getURL, getURLSearchParams, localCache, sleep, toDataUrl, unique, openPage } from './_misc'
export { isMac, isFirefox, isEdge, isBrave, isChinese, isSimpleChinese } from './_env'
export { default as openUrlInSameTab } from './_openUrlInSameTab'
